language: php

cache:
  directories:
    - $HOME/.composer/cache

php: 7.0

install:
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - composer global require friendsofphp/php-cs-fixer "^2.0.0@dev"
    - composer global require satooshi/php-coveralls "^1.0.0"
    - composer update --no-interaction

before_script:
    - if php -v | grep -q 'Xdebug'; then coverage="--coverage-clover build/logs/clover.xml"; fi

script:
    - php-cs-fixer fix --dry-run
    - vendor/bin/phpunit $coverage

after_success:
- if [[ ! -z $coverage ]]; then coveralls; fi

deploy:
    provider: script
    script:
        - vendor/bin/statie generate
        - vendor/bin/statie push-to-github enumag/enumag.cz --token=${GH_TOKEN}
    on:
        branch: gh-pages

env:
  global:
    # go to: Gitub User => Settings => Personal Access Token => Generate New Token
    # select "Repo" scope    
    # run in shell in git root: travis encrypt GH_TOKEN=<code>

    # if repo is not recognized by travis api, go to https://travis-ci.org/<repository-slug>, like githu.com/<repository-slug>
    # and add it there; like you do when you want to run tests on some repository
    - secure: 
