language: php

cache:
  directories:
    - $HOME/.composer/cache

php: 7.0

before_script:
    - phpenv config-rm xdebug.ini
    - composer update --no-interaction

script:
    - vendor/bin/phpunit

deploy:
    provider: script
    script: ./bin/deploy-gh-pages.sh
    on:
        branch: master
