language: php

php: 7.0

branches:
    only:
        - master

env:
    global:
        - secure:

before_script:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer update --prefer-source

script:
    - ./bin/deploy-gh-pages.sh

