language: php

cache:
  directories:
    - $HOME/.composer/cache

php: 7.0

install:
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - composer global require friendsofphp/php-cs-fixer "^2.0.0@dev"
    - composer global require satooshi/php-coveralls "^1.0.0"
    - composer update --no-interaction

before_script:
    - if php -v | grep -q 'Xdebug'; then coverage="--coverage-clover build/logs/clover.xml"; fi

script:
    - php-cs-fixer fix --dry-run
    - vendor/bin/phpunit $coverage

after_success:
- if [[ ! -z $coverage ]]; then coveralls; fi

deploy:
    provider: script
    script: ./bin/deploy-gh-pages.sh
    on:
        branch: master
